// Shared skill-graph data layer. Both the 3D graph and the grid view read from
// src/skillgraph.json (generated by `npm run embed-skills`), so a single source
// drives both presentations.

import graph from "../skillgraph.json";

export interface GraphNode {
  id: string;
  category: string;
  color: string;
  isHub: boolean;
  x: number;
  y: number;
  z: number;
  level?: string;
  description?: string;
  icon?: string;
}

export interface GraphLink {
  source: string;
  target: string;
  weight: number;
  kind: "semantic" | "member";
}

export interface CategoryMeta {
  name: string;
  icon: string;
  color: string;
}

export interface SkillItem {
  title: string;
  level: string;
  description: string;
}

export interface SkillCategory {
  category: string;
  icon: string;
  color: string;
  items: SkillItem[];
}

export const graphNodes = graph.nodes as unknown as GraphNode[];
export const graphLinks = graph.links as unknown as GraphLink[];
export const categoryMeta = graph.meta.categories as unknown as CategoryMeta[];

/** Reconstruct the category → items grouping the grid view expects. */
export const skillCategories: SkillCategory[] = categoryMeta.map((cat) => ({
  category: cat.name,
  icon: cat.icon,
  color: cat.color,
  items: graphNodes
    .filter((n) => !n.isHub && n.category === cat.name)
    .map((n) => ({
      title: n.id,
      level: n.level ?? "intermediate",
      description: n.description ?? "",
    })),
}));

/** Look up a full category (with items) by name — used when a hub is clicked. */
export function categoryByName(name: string): SkillCategory | undefined {
  return skillCategories.find((c) => c.category === name);
}
